services:
  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: ml-api
    ports:
      - "8000:8000"
    volumes:
      # Persist Django default SQLite DB (db.sqlite3) in your project folder
      - ./ml:/app:z
    networks:
      - appnet

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui-web
    ports:
      - "8080:80"
    depends_on:
      - ml
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
