ACCEPT schema PROMPT 'Enter schema name: '

SET LINESIZE 300
SET PAGESIZE 100
COLUMN OWNER FORMAT a20
COLUMN TABLE_NAME FORMAT a50
COLUMN TABLESPACE_NAME FORMAT a30
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME, NUM_ROWS, LAST_ANALYZED
FROM ALL_TABLES
WHERE OWNER = UPPER('&schema')
ORDER BY TABLE_NAME;